# Generated by Django 4.1.3 on 2022-11-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_rename_jobs_myjobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyJobs',
            new_name='MyJob',
        ),
    ]
