# Generated by Django 4.1.3 on 2022-11-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_myjob_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjob',
            name='companysign',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='myjob',
            name='descripiton',
            field=models.TextField(default=''),
        ),
    ]
