# Generated by Django 4.1.3 on 2022-11-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_myjob_companysign_alter_myjob_descripiton'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=150)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.myjob')),
            ],
        ),
    ]
