# Generated by Django 4.1.3 on 2022-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_jobduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobduty',
            name='importance',
            field=models.IntegerField(choices=[(0, 'Very Low'), (1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Very High')], default=0),
        ),
    ]
