# Generated by Django 4.1.3 on 2022-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('time', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MyEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=64)),
                ('univeristyname', models.CharField(max_length=128)),
                ('period', models.CharField(max_length=64)),
                ('univeristysign', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
