# Generated by Django 4.1.3 on 2022-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myedu',
            name='univeristytopic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
