# Generated by Django 4.1.3 on 2022-11-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Advanced'), ('3', 'Competent'), ('4', 'Proficient'), ('5', 'Expert')], max_length=1)),
            ],
        ),
    ]
